# Docker konfiguracija koja se koristi pre produkcije jer imamo dodatni mongo express
# kao klijnetsku stranu kao GUI sa prikazom nase mongo baze podataka
version: '3.9'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: nosql
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks: 
      - net_mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - type: volume
        source: data_db
        target: /data/conf

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - net_mongo
      
networks:
    net_mongo:

volumes: 
    data_db: