FROM continuumio/anaconda3

WORKDIR /home/app/backend
COPY ./backend ./

RUN conda update -n base -c defaults conda
RUN conda config --set restore_free_channel true
RUN conda env create -f ./env/environment.yml
RUN echo "source activate myenv" > ~/.bashrc

ENV PATH /opt/conda/envs/myenv/bin:$PATH

WORKDIR /home/app