FROM node as build-front

WORKDIR /build-app
COPY ./front/package.json ./front/package-lock.json ./
RUN npm i
COPY ./front ./
COPY ./nginx.conf ./
RUN npm run build

FROM nginx:1.12-alpine

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build-front /build-app/dist/front .
COPY --from=build-front /build-app/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]