version: '3.9'
services:
  mongo:
    container_name: mongo_nosql_pedja
    image: mongo
    restart: always
    command: mongod --auth
    environment:
      MONGO_INITDB_DATABASE: pedja_nosql
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks: 
      - net_mongo
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: data_db
        target: /data/conf

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - net_mongo

  arango:
    container_name: pedja_arango
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: root   #user=root(default)
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps
      
networks:
    net_mongo:

volumes: 
    data_db:
    arangodb_data_container:
    arangodb_apps_data_container:
