version: '3.8'

services:
  mysql:
    restart: always
    image: mysql:latest
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
    ports:
      - '3306:3306'
volumes:
  todo-mysql-data:
