version: '3.8'

services:
  mongo-express:
    container_name: mongo-ui
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongo_db
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    networks:
      - mongo-compose-network
    ports:
      - 8081:8081
  mongo_db:
    container_name: mongo_db_pedja
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongo-compose-network
volumes:
  mongodb_data_container:

networks:
  mongo-compose-network:
    driver: bridge